#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SmartXbar
Version  : 4.1.0
Release  : 1
URL      : https://github.com/intel/SmartXbar/archive/v4.1.0.tar.gz
Source0  : https://github.com/intel/SmartXbar/archive/v4.1.0.tar.gz
Summary  : SmartXbar
Group    : Development/Tools
License  : BSD-3-Clause
Requires: SmartXbar-bin = %{version}-%{release}
Requires: SmartXbar-data = %{version}-%{release}
Requires: SmartXbar-lib = %{version}-%{release}
Requires: SmartXbar-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : googletest-dev
BuildRequires : libsndfile-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(AudioCommon)
BuildRequires : pkgconfig(automotive-dlt)
BuildRequires : tbb-dev
Patch1: 0001-modify-config-for-clear-linux-stateless.patch

%description
# SmartXbar

%package bin
Summary: bin components for the SmartXbar package.
Group: Binaries
Requires: SmartXbar-data = %{version}-%{release}
Requires: SmartXbar-license = %{version}-%{release}

%description bin
bin components for the SmartXbar package.


%package data
Summary: data components for the SmartXbar package.
Group: Data

%description data
data components for the SmartXbar package.


%package dev
Summary: dev components for the SmartXbar package.
Group: Development
Requires: SmartXbar-lib = %{version}-%{release}
Requires: SmartXbar-bin = %{version}-%{release}
Requires: SmartXbar-data = %{version}-%{release}
Provides: SmartXbar-devel = %{version}-%{release}

%description dev
dev components for the SmartXbar package.


%package lib
Summary: lib components for the SmartXbar package.
Group: Libraries
Requires: SmartXbar-data = %{version}-%{release}
Requires: SmartXbar-license = %{version}-%{release}

%description lib
lib components for the SmartXbar package.


%package license
Summary: license components for the SmartXbar package.
Group: Default

%description license
license components for the SmartXbar package.


%prep
%setup -q -n SmartXbar-4.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542696145
mkdir -p clr-build
pushd clr-build
%cmake .. -DCMAKE_INSTALL_LIBDIR=%{_lib}
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1542696145
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SmartXbar
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/SmartXbar/LICENSE.txt
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/share/cmake/
mv %{buildroot}/usr/lib64/ias-audio-smartx/ %{buildroot}/usr/share/cmake/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/vads

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*
/usr/share/defaults/SmartXbar/smartx_config.txt

%files dev
%defattr(-,root,root,-)
/usr/include/smartxbar/audio/configparser/IasSmartXDebugFacade.hpp
/usr/include/smartxbar/audio/configparser/IasSmartXconfigParser.hpp
/usr/include/smartxbar/audio/equalizerx/IasEqualizerCmd.hpp
/usr/include/smartxbar/audio/mixerx/IasMixerCmd.hpp
/usr/include/smartxbar/audio/smartx/IasConnectionEvent.hpp
/usr/include/smartxbar/audio/smartx/IasEvent.hpp
/usr/include/smartxbar/audio/smartx/IasEventHandler.hpp
/usr/include/smartxbar/audio/smartx/IasEventProvider.hpp
/usr/include/smartxbar/audio/smartx/IasIDebug.hpp
/usr/include/smartxbar/audio/smartx/IasIProcessing.hpp
/usr/include/smartxbar/audio/smartx/IasIProcessingModuleConfig.hpp
/usr/include/smartxbar/audio/smartx/IasIRouting.hpp
/usr/include/smartxbar/audio/smartx/IasISetup.hpp
/usr/include/smartxbar/audio/smartx/IasProperties.hpp
/usr/include/smartxbar/audio/smartx/IasSetupEvent.hpp
/usr/include/smartxbar/audio/smartx/IasSetupHelper.hpp
/usr/include/smartxbar/audio/smartx/IasSmartX.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasAudioPlugin.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasAudioStream.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasBaseAudioStream.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasBundledAudioStream.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasGenericAudioComp.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasGenericAudioCompCore.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasICmdRegistration.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasIGenericAudioCompConfig.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasIModuleId.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasModuleEvent.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasModuleInterface.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasModuleLoader.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasPluginLibrary.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasProcessingTypes.hpp
/usr/include/smartxbar/audio/smartx/rtprocessingfwx/IasSimpleAudioStream.hpp
/usr/include/smartxbar/audio/testfwx/IasTestFramework.hpp
/usr/include/smartxbar/audio/testfwx/IasTestFrameworkPublicTypes.hpp
/usr/include/smartxbar/audio/testfwx/IasTestFrameworkSetup.hpp
/usr/include/smartxbar/audio/volumex/IasVolumeCmd.hpp
/usr/lib64/libias-audio-configparser.so
/usr/lib64/libias-audio-smartx.so
/usr/lib64/libias-audio-testfwx.so
/usr/lib64/pkgconfig/SmartXbar.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libias-audio-configparser.so.4
/usr/lib64/libias-audio-configparser.so.4.1.0
/usr/lib64/libias-audio-smartx.so.4
/usr/lib64/libias-audio-smartx.so.4.1.0
/usr/lib64/libias-audio-testfwx.so.4
/usr/lib64/libias-audio-testfwx.so.4.1.0
/usr/lib64/smartx-plugin/pluginias-audio-modules.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SmartXbar/LICENSE.txt
